### ISSUE TITLE
Reloading not enabled in GroovyPagesTemplateRenderer

### ISSUE THREAD

**Issue by hayeskl** [grails/grails-gsp#238]
The GroovyPagesTemplateRenderer is not being initialized properly.

### Expected Behaviour

Tell us what should happen
```
GroovyPagesGrailsPlugin:223 should register the bean with reloading:
     groovyPagesTemplateRenderer(GroovyPagesTemplateRenderer) { bean ->
            bean.autowire = true
            if (enableReload) {
                reloadEnabled = enableReload
            }
        }
```
### Actual Behaviour
  The GroovyPagesTemplateRenderer is currently getting the reloadEnabled from the GroovyPagesTemplateEngine, but when it checks for reloading it hasn't been set on the GroovyPagesTemplateEngine yet so it always ends up as false.

### Environment Information
Grails 5.0.1

**Comment by jeffscottbrown** [comment]
@hayeskl This is great feedback.  Thank you!

Are you willing to submit a PR to help with this?
