### ISSUE TITLE
TagLibraryInvoker should not modify globally registered ExpandoMetaClass in development mode

### ISSUE THREAD

**Issue by zyro23** [grails/grails-gsp#42]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

this is a follow-up of grails/grails-core#11358

pull-request follows.

### Expected Behaviour

`TagLibraryInvoker` `ExpandoMetaClass` modifications should not survive a boot devtools restart in development mode.

### Actual Behaviour
the `ExpandoMetaClass` methods used for cross-taglib tag-as-method invocations are persisted across devtools restarts (as they are set on a globally registered ExpandoMetaClass).

note that while `TagLibraryInvoker.methodMissing` is lacking the development guard, `TagLibraryInvoker.propertyMissing` does it already:  
https://github.com/grails/grails-gsp/blob/v4.0.0.RC1/grails-web-taglib/src/main/groovy/grails/artefact/gsp/TagLibraryInvoker.groovy#L115-L117

### Environment Information

- **Operating System**: win x64
- **Grails Version:** 4.0.0.RC2
- **JDK Version:** oracle 8u121
- **Container Version (If Applicable):** n/a

### Example Application

see referenced issue

**Comment by zyro23** [comment]
@graemerocher you were right in the pull-request discussion that the merged fix does not cover all situations.

we now see a similar issue when modifying/reloading an application `TagLib` class.  
i think it is this line: https://github.com/grails/grails-gsp/blob/v4.0.0.RC1/grails-plugin-gsp/src/main/groovy/org/grails/plugins/web/GroovyPagesGrailsPlugin.groovy#L320

with devtools restart, do we even need `GroovyPagesGrailsPlugin#onChange` any longer?

thank you!

**Comment by graemerocher** [comment]
Don't think so

**Comment by zyro23** [comment]
the taglib-reloading related issue occurred in an app that did not use `org.grails:grails-web-taglib:4.0.0.BUILD-SNAPSHOT` but still `4.0.0.RC2` - after using `4.0.0.BUILD-SNAPSHOT` (including the merged pr), no more problem.

so while `GroovyPagesGrailsPlugin#onChange` is modifying an `ExpandoMetaClass` (and may be superficial), it looks like its not actively causing problems.  
i guess thats because it just modifies the metaClass of the changed taglib which belongs to the restart classloader.  
and that gets replaced by the devtools restart right after `onChange` is invoked.

**Comment by davydotcom** [comment]
Based on discussion. this looks to be resolved. Alose, the `GroovyPagesGrailsPlugin#onChange` is still useful with spring-loaded in grails 4.0.x using java 8. Should leave this for now.
