### ISSUE TITLE
Migrate to Develocity build cache connector 

### ISSUE THREAD

**Issue by puneetbehl** [grails/grails-gsp#432]
Apply Change similar to https://github.com/grails/grails-core/pull/13387

**Comment by puneetbehl** [comment]
@guillermocalvo Can you please create issues similar to this for other Grails projects and assign to either @Richardson-e or @weiqigao ?

**Comment by guillermocalvo** [comment]
@puneetbehl 👍 I just created a bunch of them:

- https://github.com/grails/gorm-graphql/issues/143
- https://github.com/grails/grails-forge/issues/284
- https://github.com/grails/gorm-neo4j/issues/626
- https://github.com/grails/grails-async/issues/105
- https://github.com/grails/gorm-mongodb/issues/699
- https://github.com/grails/grails-functional-tests/issues/209
- https://github.com/grails/grails-views/issues/522
- https://github.com/grails/grails-data-mapping/issues/1788
- https://github.com/grails/grails-cache/issues/179
- https://github.com/grails/grails-testing-support/issues/371
- https://github.com/grails/grails-gradle-plugin/issues/284
- https://github.com/grails/grails-spring-security-oauth2/issues/77
- https://github.com/grails/grails-redis/issues/151
- https://github.com/grails/grails-spring-security-core/issues/1000
- https://github.com/grails/grails-spring-security-cas/issues/104
- https://github.com/grails/grails-plugin-converters/issues/25
