### ISSUE TITLE
g:formatDate issue with java.sql.Date class instances

### ISSUE THREAD

**Issue by manishkbharti** [grails/grails-gsp#50]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Add the following code in any action
```
java.sql.Date date = new java.sql.Date(Calendar.getInstance().getTime().getTime())
g.formatDate(date: date, format: 'yyyy/MM/dd')
```
2. Run the application and hit that action
3. you will get `java.lang.UnsupportedOperationException`

### Expected Behaviour

java.sql.Date instance should be formated.

### Actual Behaviour

Getting `java.lang.UnsupportedOperationException`

### Environment Information

- **Operating System**: Any
- **Grails Version:** 4.0.2
- **JDK Version:** 8
- **Container Version (If Applicable):** NA

### Example Application

- https://github.com/manishkbharti/bindingFormatIssueDemo
1. Run the application
2. Hit http://localhost:8080/test/testDateFormat url
3. Error page displayed with message `java.lang.UnsupportedOperationException`

**Comment by manishkbharti** [comment]
Workaround --

```
    java.sql.Date date = new java.sql.Date(Calendar.getInstance().getTime().getTime())
    g.formatDate(date: date.getTime(), format: 'yyyy/MM/dd')
````

**Comment by jeffbrown** [comment]
For reference: https://stackoverflow.com/questions/60717923/gformatdate-issue-with-java-sql-date-class-instances
