### ISSUE TITLE
create grails-gsp 6.2.4 release for Grails 6.2.2

### ISSUE THREAD

**Issue by jamesfredley** [grails/grails-gsp#546]
https://docs.google.com/document/d/177i1DJ6iPtuvziXrcMoIOImVqJXfIFxLlOIS5sre72I/edit?tab=t.0#heading=h.iv8c37f5fktv

GSP requires https://github.com/grails/grails-gradle-plugin/issues/353 to remove `-plain` in jar filename.

**Comment by matrei** [comment]
https://github.com/grails/grails-gsp/pull/547
