### ISSUE TITLE
New GroovyPageCompilerForkTask seems to ignore Configuration (of codecs)

### ISSUE THREAD

**Issue by hansmaulwurf23** [grails/grails-gsp#63]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. create a new grails 4.0.4 application
2. edit the generated `grails-app/views/index.gsp` add 
```html
<head>
...
  <script>
    var foo = ${[a:23, b:42, c:666] as grails.converters.JSON};
  </script>
</head>
```
3. set the codecs in `application.yml` to the following
```yml
grails:
  views:
    gsp:
      codecs:
        expression: none
```

### Expected Behaviour

`grails-app/views/index.gsp` shows up as
```javascript
var foo = {"a":23,"b":42,"c":666};
```
### Actual Behaviour

The same when running in development. In the packaged war file (deployed to Tomcat or running with `java -jar build/libs/foo.war`) the `grails-app/views/index.gsp` shows up as

```javascript
var foo = {&quot;a&quot;:23,&quot;b&quot;:42,&quot;c&quot;:666};
```

### Environment Information

- **Operating System**: Linux
- **Grails Version:** 4.0.4
- **JDK Version:** 11
- **Container Version (If Applicable):** Tomcat

### Full Description

Since this was working in grails 4.0.3 (see [Stackoverflow](https://stackoverflow.com/questions/63505103/expression-codec-grails-views-gsp-codecs-expression-seems-to-be-ignored-in-dep)) the problem seems to be in the new [GroovyPageCompilerForkTask](https://github.com/grails/grails-gsp/commits/master/grails-web-gsp/src/main/groovy/org/grails/web/pages/GroovyPageCompilerForkTask.groovy). The `GroovyPageCompilerForkTask` is invoked with the config file location but never used: https://github.com/grails/grails-gsp/blob/6a575c1c0e4b87752752367c9036a83dc35725ad/grails-web-gsp/src/main/groovy/org/grails/web/pages/GroovyPageCompilerForkTask.groovy#L117-L121 
The calling site in `grails-core` has a hard coded argument https://github.com/grails/grails-core/blob/ae8e2738821fcef78fb40dae51a6131a392baab8/grails-gradle-plugin/src/main/groovy/org/grails/gradle/plugin/web/gsp/GroovyPageForkCompileTask.groovy#L96 (which is probably not the best idea as well ;-))

Thanks for the great work on Grails and @frnktrgr for the digging!

**Comment by davydotcom** [comment]
Finally looking into this sorry, should just be a matter of uncommenting that line im testing it now. Don't remember why it was uncommented. Also the hard coded path was leftover copied from the old.
