### ISSUE TITLE
Query in Grails, IMPORTANT

### ISSUE THREAD

**Issue by AdithyaPM** [grails/grails-gsp#81]
I have a table consisting of 2 parameters(name and calendar).I have created the dropdown using <g:select> tag that consists list of names from the table,on selection I want to fetch the corresponding calendar and display it.Any idea how can I fetch the calendar related to name?

this is my gsp code which gives list of names as dropdown

`<g:select class="form-control" id="savedCalendar" name="savedCalendar.id" noSelection="['null':'']" from="${globalCalendar?.name}" onchange="return showcal()"/>`

what should I do in function so that I can fetch calendar and display it

`function showcal(){

           ????
}`

Please guide me on this, I searched everywhere and coudn't get the approach for this
Thanks in advance

**Comment by puneetbehl** [comment]
@AdithyaPM I think [Grails Slack](grails.slack.com) is the best place to get answer to your questions.
